### ISSUE TITLE
Triage issues

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1317]
We need to triage existing bugs mainly in the [thimble.webmaker.org](https://github.com/mozilla/thimble.webmaker.org/issues) and [brackets](https://github.com/humphd/brackets/issues) repos to reflect a realistic and achievable bug list that will help engage potential contributors and show more or less in which direction Thimble is heading.

We should probably have a discussion in this ticket about which issues we would like to close/keep open and why and follow up accordingly. Another suggestion is to schedule a video call (which has also worked well in the past).

cc @simonwex @hannahkane @flukeout

**Comment by flukeout** [comment]
I took a first pass at organizing all of the [Current Bugs](https://github.com/mozilla/thimble.webmaker.org/issues?q=is%3Aopen+is%3Aissue+label%3Abug)

**Feels important**
* [ ] #1277 Allow anchors within tutorial
* [ ] #1311 - "Saving Failed, Retrying.." error

**Less important**
* [ ] #1306 Project rename loses focus
* [ ] #1279 Tutorial tab still visible
* [ ] #1249 Preview bar icon size & alignment
* [ ] #1239 Extra click in Firefox
* [ ] #1230 Deleted images appear in preview
* [ ] #1227 Moving files UX
* [ ] #1200 Future date in projects table
* [ ] #1174 LESS style updates not immediate
* [ ] #1154 Preview header moves when window narrow
* [ ] #719 Make project rename count as 'update'
* [ ] #676 Right click menu color
* [ ] #671 Quick docs not available for img tag
* [ ] #634 Initial file not shown as selected in tray
* [ ] #591 Unexpected Command + K behaviour   

**Resolved by existing PR**
* [ ] #1309 Bad styles in tutorial

**Comment by hannahkane** [comment]
@flukeout - I like your bug triage list. I added P1 labels to the two in "Feels Important."

@gideonthomas - did you want to triage other issues as well, including feature requests? I think that would be useful, and was hoping to do that next week, maybe when @Pomax is back from PTO. Would love to follow up with some communications to community.

**Comment by gideonthomas** [comment]
yeah that sounds like a great idea!

**Comment by hannahkane** [comment]
On second thought, there are probably too many tickets for a useful vidyo chat, so maybe we can do some more async categorization until we have a smaller number of issues we need to talk about.

FWIW, my thoughts about priority are suggested in the [roadmap](https://github.com/mozilla/thimble.webmaker.org/wiki/Roadmap).  Top priority = localization and shutting down old Thimble. After that, I'd love to focus on a) discovery of projects and b) measuring learning. The former is quite UX-heavy, and the latter is quite metrics-heavy, so these are perhaps not the best projects for new contributors.

Would be useful for someone to go through and identify issues that don't require a lot of conversation or UX work—perhaps those could be marked as "good first bug" or "needs help."

**Comment by gideonthomas** [comment]
I added the "good first bug" tag to a couple of issues. 

Adding to @flukeout's comment, how do we want to deal with the "less important" issues? Should we close them? Or should we mark them with a "wontfix" tag?

Here are some more issues that I think we should consider closing:

Close | "wontfix" | Leave open | Issue
-------- | ----------- | ---------------- | -------
<ul><li>- [ ] </li> | <ul><li>- [ ] </li> | <ul><li>- [ ] </li> | #1323 Thimble zoomed in iOS Safari
<ul><li>- [ ] </li> | <ul><li>- [ ] </li> | <ul><li>- [ ] </li> | #1302 Let Thimble work when services are down
<ul><li>- [ ] </li> | <ul><li>- [ ] </li> | <ul><li>- [ ] </li> | #1257 Refreshing quickly shows incorrect preview
<ul><li>- [ ] </li> | <ul><li>- [ ] </li> | <ul><li>- [ ] </li> | #1240 Heavy JS "may" be slowing down the editor
<ul><li>- [ ] </li> | <ul><li>- [ ] </li> | <ul><li>- [ ] </li> | #1236 Link navigation in the preview using JS
<ul><li>- [ ] </li> | <ul><li>- [ ] </li> | <ul><li>- [ ] </li> | #1202 More info in the `publishedProjects` table
<ul><li>- [ ] </li> | <ul><li>- [ ] </li> | <ul><li>- [ ] </li> | #1200 Random invalid date for a project in the db
<ul><li>- [ ] </li> | <ul><li>- [ ] </li> | <ul><li>- [ ] </li> | #1139 Inform roadmap formulation based on JSBin
<ul><li>- [ ] </li> | <ul><li>- [ ] </li> | <ul><li>- [ ] </li> | #1134 Custom templates for new HTML files
<ul><li>- [ ] </li> | <ul><li>- [ ] </li> | <ul><li>- [ ] </li> | #983 Codebase cleanup
<ul><li>- [ ] </li> | <ul><li>- [ ] </li> | <ul><li>- [ ] </li> | #958 Upload files via url
<ul><li>- [ ] </li> | <ul><li>- [ ] </li> | <ul><li>- [ ] </li> | #707 Vanity paths for published projects

@hannahkane, @flukeout - feel free to put a checkmark in any of the columns to indicate your thoughts. I personally feel like all of them should be closed.

**Comment by hannahkane** [comment]
I'm +1 on closing all of these. One that gave me pause is #958, because I think it adds value, but still okay to close, so we can focus more exclusively on l10n and planning/research. The work implied in #1139 would need to be revived if/when we move forward with more project discovery tools, but am okay with closing now.

**Comment by gideonthomas** [comment]
I'll label #958 and #1139 as P3s then so that it'll be easier to access them later on.

**Comment by flukeout** [comment]
I'm okay with closing those as well.

**Comment by gideonthomas** [comment]
Ok, all issues in this repo now have either a P1, P2 or P3 tag attached to them. I did this based on what I saw in the roadmap for v2.4 and v2.5. @hannahkane and @flukeout feel free to take a look and change any of the tags that you feel need to be changed (especially the ones re: learning).

As it stands right now the count for each tag is:
[P1 issues](https://github.com/mozilla/thimble.webmaker.org/labels/P1) - 7
[P2 issues](https://github.com/mozilla/thimble.webmaker.org/labels/P2) - 24
[P3 issues](https://github.com/mozilla/thimble.webmaker.org/labels/P3) - 49
Total open issues - 80

**Comment by simonwex** [comment]
Could you describe your delineation for P1/2/3?

**Comment by gideonthomas** [comment]
Sure, here was my thought process for it:
P1 - Localization and transitioning from old-Thimble as per [v2.3](https://github.com/mozilla/thimble.webmaker.org/wiki/Roadmap#v23-full-parity) + [urgent technical debt](https://github.com/mozilla/thimble.webmaker.org/issues/1320#issue-125042573) + unrecoverable issues
P2 - Less urgent technical debt + making thimble more social (discovery of projects and making publishing a smoother experience, public analytics) as per [v2.4](https://github.com/mozilla/thimble.webmaker.org/wiki/Roadmap#v24-share-and-discover)
P3 - Feature requests that we may implement (re-triage later on) + Least important technical debt (re-triage later on) + learning tools as per [v2.5](https://github.com/mozilla/thimble.webmaker.org/wiki/Roadmap#v25-learning) + thimble modes

Just to add to my previous comment, I added similar priority tags to the brackets and publish repos as well and here are the stats for them:

Priority | Brackets | Publish
--------- | ------------ | ----------
P1 | [3](https://github.com/humphd/brackets/labels/P1) | [4](https://github.com/mozilla/publish.webmaker.org/labels/P1)
P2 | [5](https://github.com/humphd/brackets/labels/P2) | [3](https://github.com/mozilla/publish.webmaker.org/labels/P2)
P3 | [25](https://github.com/humphd/brackets/labels/P3) | [15](https://github.com/mozilla/publish.webmaker.org/labels/P3)

**Comment by hannahkane** [comment]
The priority labels on Thimble tickets look right on to me. Feels good to have this kind of clarity. Thanks, @gideonthomas.

**Comment by gideonthomas** [comment]
Closing since we've done this
