### ISSUE TITLE
Localization Tracker

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#1318]
META bug to track all the l10n related tickets from this repo and the dependent projects (brackets, publish.wm.org, etc.)

### Technical planning ticket:
 - [ ] #1331 

### Thimble
- [ ] #475 - Discussion bug
- [ ] #662 - Language preferences from id.wm.org
- [ ] #1335 - Design UI & UX for displaying and changing the language

---
### Brackets
- [ ] [#311](https://github.com/humphd/brackets/issues/311) - General extension l10n
- [ ] [#293](https://github.com/humphd/brackets/issues/293) - Selfie-taker l10n
- [ ] [#320](https://github.com/humphd/brackets/issues/320) - HTML docs l10n

---
### Publish

---

**Comment by flukeout** [comment]
@gideonthomas Added #1335 to the above list for tracking UI & UX design.

**Comment by gideonthomas** [comment]
Closing due to redundancy. See https://github.com/mozilla/thimble.webmaker.org/issues?q=is%3Aissue+is%3Aopen+label%3ALocalization for more info.
