### ISSUE TITLE
Design and Implement the Publishing Service API (PSA)

### ISSUE THREAD

**Issue by humphd** [mozilla/thimble.webmaker.org#486]
We're moving to a world where Thimble can deal with a directory tree of files and folders vs. just a single HTML file.  We need to rework our publishing/loading so that it can support dealing with complex trees of files.

**UPDATE** (to be solved): 
* [ ] [Hook up brackets to use thimble's filesystem](https://github.com/humphd/brackets/issues/305)
* [ ] [Create a project managment layer in thimble using makedrive](https://github.com/mozilla/thimble.webmaker.org/issues/531)
* [ ] [Implement an auth solution for publish ](https://github.com/mozilla/makedrive/issues/480)
* [ ] [Create database layer for managing user metadata, filesystem blocks and project status](https://github.com/mozilla/makedrive/issues/483)
* [ ] [Create `publish` API](https://github.com/mozilla/makedrive/issues/484)
* [ ] [Deploy `publish` server to staging](https://github.com/mozilla/makedrive/issues/485)
* [ ] [Add "save" functionality for multi-file projects](https://github.com/mozilla/thimble.webmaker.org/issues/535)
* [ ] [Build UX for project selection, opening, saving and remixing](https://github.com/mozilla/thimble.webmaker.org/issues/536)

**Roadmap**:  https://etherpad.mozilla.org/thimble-plublish-plan

**Comment by humphd** [comment]
One option suggested by @jbuck today is to try and leverage prior art in the following patches:
* https://github.com/mozilla/webmaker-app/pull/966
* https://github.com/mozilla/webmaker-app-publisher/pull/10

These provide an implementation of http://docs.aws.amazon.com/AmazonS3/latest/API/sigv4-UsingHTTPPOST.html, and there are a bunch of node modules that Jon has done to do the annoying bits of signing requests for you (details unknown).

Whether we want to talk directly to S3 from the browser or not, I don't know.  CC'ing @davidascher, @simonwex, @jbuck for thoughts.  My question: should we use our node.js server side code to do this, or make it work by doing it directly from the browser filesystem (filer) to S3?

**Comment by humphd** [comment]
CC'ing @k88hudson too, since she seems to have reviewed a lot of this code, and likely has some wisdom.

**Comment by sedge** [comment]
I think we might have to use the nodejs server if the act of publishing requires an oauth2 access token. Is there a way around that?

**Comment by humphd** [comment]
@jbuck has server-side bits in https://github.com/mozilla/webmaker-app-publisher/pull/10, which I assume we'll need to do as well, yeah.

**Comment by jbuck** [comment]
So, I know I'm going against what I said before, but I don't think you should use S3 for bramble. I think the ideal setup is you have your relational database that the editor read/writes to. Then you write another server that only reads from this database. It's easy to run/test locally, and you get all of the security benefits of serving stuff up from another domain.

**Comment by sedge** [comment]
* Build an app w/ db
  * Projects of files live here
* Each project has a file tree
* Each project is published completely when published
* Local saving persists until logout, or if you switch projects
* Each project needs to have paths transformed to match the published root (TBD, not a first step)
* IndexDB will be shared between tabs... needs to be considered.

**Comment by Pomax** [comment]
feature request: "export to". If I have an S3 key and I want to push my entire tree up to S3, that should be a thing I can do. Do I have heroku creds? let me push straight to heroku. Github API key in my pocket? Let me push to my repo's gh-pages branch.

Files that live inside my browser and need to be "downloaded out" does not feel like a path to victory, but a roadblock that gets in the way of doing what I want to do, and then sending it out into the world.

**Comment by sedge** [comment]
Our first attempt at charting the UX for multi-file publishing, along with the technical requirements,  is outlined here:  https://etherpad.mozilla.org/thimble-plublish-plan

**Comment by jbuck** [comment]
# Publishing Service API (PSA) Proposal

Create a new API server responsible for storing and viewing published content.

## Use cases
* Publish a Goggles Remix
* Publish multiple files in Bramble
* Renaming a project
* Renaming a file within a project

## Definitions
* username - Webmaker username
* project - The name of the project. A container belonging to a single user for a collection of files
* filename - The filename of the file being published. This can include "/" for directories, so you could have "index.html" or "examples/index.html". However, each file must live within the username/project container.

## API
* `GET /:username`
  * Return a list of projects associated with the user
* `GET /:username/:project`
  * Return a list of files associated with the project
* `GET /:username/:project/:filename`
  * Return the content of the specified path
* `PUT /:username/:project/:filename`
  * Store the request body at the specified path
* `DELETE /:username/:project/:filename`
  * Delete the file of the specified path

Each GET endpoint also has a HEAD endpoint that can be used to check for metadata. Answer "Does this collection or file exist?" or "Has this collection or file changed? (via ETag)"

Possible reserved usernames for future features:
* discover
* search

![sequence diagram of publishing a new project with a title conflict](http://www.websequencediagrams.com/cgi-bin/cdraw?lz=dGl0bGUgUHVibGlzaGluZyBOZXcgUHJvamVjdAoKVXNlci0-VGhpbWJsZToAHwggcAAZBwASBy0-VXNlcjogUHJvbXB0IGZvcgAaCCBuYW1lADYQU2V0ABMNIHRvICJteS1jb29sLQBUByIAUgoAgRIKOiBIRUFEIC9qb24vACEPCgCBOAoAgSULMjAwIE9LAIEXEERpc3BsYXkgbWVzc2FnZSAiVGhlAIEDBicAdw8nIGlzIGFscmVhZHkgdGFrZW4uXG5QbGVhc2UgY2hvb3NlIGEgZGlmZmVyZW4AgWcGIgCBOjQtbmV3AIFCMC1uZXcAgWAWNDA0IE5vdCBGb3VuZACCMhZQVVQAPBkvaW5kZXguY3NzAIIvJgApL2h0bWwAgnE9AIUlB2VkIGh0dHBzOi8vbWFrZXMub3JnAIE6GSIK&s=default)
[editable diagram](http://www.websequencediagrams.com/?lz=dGl0bGUgUHVibGlzaGluZyBOZXcgUHJvamVjdCB3aXRoIGNvbmZsaWN0aW5nIHAAEgduYW1lCgpVc2VyLT5UaGltYmxlOgA9CAAdCAoAEgctPlVzZXI6IFByb21wdCBmb3IAOQ4ANw9TZXQAWg0gdG8gIm15LWNvb2wtAHkHIgBSCgCBMAo6IEhFQUQgL2pvbi8AIQ8KAIFWCgCBJQsyMDAgT0sAgRcQRGlzcGxheSBtZXNzYWdlICJUaGUAgQMGJwB3DycgaXMgYWxyZWFkeSB0YWtlbi5cblBsZWFzZSBjaG9vc2UgYSBkaWZmZXJlbgCCLgYiAIE6NC1uZXcAgUIwLW5ldwCBYBY0MDQgTm90IEZvdW5kAIIyFlBVVAA8GS9pbmRleC5jc3MAgi8mACkvaHRtbACCcT0AhUMHZWQgaHR0cHM6Ly9tYWtlcy5vcmcAgToZIgo&s=default)

**Comment by sedge** [comment]
This is really really helpful, and covers our bases really well. I particularly like the HEAD/GET combination. A few initial thoughts:

* There's no route for deleting a project vs deleting a file. I can see an argument for both sides of that decision
* There's no distinction between published and unpublished projects. This means we'll have to deal with some edge cases to do with local work and user expectations. Maybe taking invisible snapshots and removing all UX to do with "saving" in the editor is the way to go?
* Users will have to know the filename of the `html` document they're trying to open in order to access a project. This isn't so bad

**Comment by humphd** [comment]
* `GET /:username/:project`
    * Return a list of files associated with the project

Question: how will sub-folders work?  How will I know that something named `project/foo` is a folder vs. a file?  Can this return something more like an fs stat, and allow us to walk the tree when opening the project?
```js
[
  {
    name: "filename.html",
  },
  {
    name: "foo",
    isDirectory: true
  },
  ...
]
```
Combined with this, we'd need a way to have a directory entry return a similar JSON listing vs. the contents.  An alternative would be to send the entire tree vs. just the top level dir contents:

```js
[
  {
    name: "filename.html",
  },
  {
    name: "foo",
    children: [
      {
        name: "filename.html",
      },
      ...
    ]
  },
  ...
]
```
This might be the best option, since it let's us recreate the recursive tree and start requesting files be downloaded one by one.

@sedge, I think we've agreed that anything on the server is always "published."  Saving just means "in the local browser filesystem."

@jbuck, how will a user navigate to this project?  Will you have yet another domain that sits on top of this published datastore and gives HTTP-style read access?

**Comment by humphd** [comment]
@jbuck do you imagine this publishing API being accessed from node, the browser or both?

**Comment by gideonthomas** [comment]
* `GET /:username/:project`
 * Return a list of files associated with the project

As a suggestion, consider changing it to:
* `HEAD /:username/:project`
 * Return a list of files associated with the project (with @humphd's stat solution) because I don't think any other metadata would be relevant to us

While,
* `GET /:username/:project` will
 * Return the contents of `/:username/:project/index.html` which would probably make the UX a bit better

**Comment by sedge** [comment]
@gideonthomas I like that! In that case the `HEAD /:username/:project` route could still be used for checking existence (404) but will also pass data along.

**Comment by humphd** [comment]
Are we thinking to do Apache-style dir listings for users?

![](http://www.askdavetaylor.com/1-blog-pics/apache-crude-directory-listing.png)

**Comment by gideonthomas** [comment]
In terms of projects in Googles vs. projects in Thimble, on the publish server (database I guess), are we making a distinction between them (maybe a flag)? Otherwise, wouldn't that allow you to open Goggles projects in thimble and vice-versa?

@humphd If you're talking about listing contents of subdirectories, I don't think we should, i.e. `GET /:username/:projectname/:dir` I think should force `GET /:username/:projectname/:dir/index.html`, and 404 if not found. Unless I'm misunderstanding and you actually meant suffixing dirs with `/`?

**Comment by humphd** [comment]
@humphd<https://github.com/humphd> If you're talking about listing contents of subdirectories, I don't think we should, i.e. GET /:username/:projectname/:dir I think should force GET /:username/:projectname/:dir/index.html, and 404 if not found. Unless I'm misunderstanding and you actually meant suffixing dirs with /?

I mean, do we want to allow users to get access to a folder that doesn’t (and shouldn’t) have an `index.html`.  For example, an `/images` folder, or `/scripts`, `/styles`, etc.

**Comment by sedge** [comment]
@jbuck and I decided that the publish server will also have to serve as an oauth2 resource server.

**Comment by humphd** [comment]
I've morphed this bug slightly, to be about designing and implementing PSA.

Talking with @flukeout, there is another requirement that we need, specifically, a separation between content that is saved to the server, and content that is published.  The goal of this separation is that a user be able to save frequently, and potentially save broken content, without affecting the published version until they are satisfied.

From an implementation point of view:

* `PUT /:username/publish/:project`
    * Copy (i.e., snapshot the current state) of the user's saved project files for public access. If the project has never existed before or been published in the past, it will be created.  If it has already been published, it will be updated/replaced with the current file content.
* `PUT /:username/unpublish/:project`
    * Remove a previously publsihed project

Assuming we're using a database for file storage, I suggest we consider two tables:
* saved (`user, project, filename, data`)  - these rows represent files that have been (auto)saved from an app (Thimble) to the server, and may or may not be published.
* published projects (`user, project, filename, data`) - these rows have at one time been copied from the  `saved` table, and are what we serve externally via HTTP for `/:user/:project/:path`

**Comment by gideonthomas** [comment]
@humphd so @sedge and I were discussing a bit about the API for all these steps and here are our thoughts:
* Thimble-publish server communication API
 * Metadata:
  * `GET /meta/:username` - List of projects
  * `GET /meta/:username/:projectName` - List of contents of a project along with other info (is it published, etc.). 404 if `projectName` does not exist
  * `GET /meta/:username/:projectName/dir` - List of contents of the dir. 404 if `dir` does not exist
 * File operations:
  * `PUT /:username/:projectName/file` - Update the contents of the file (or create if it does not exist)
  * `DELETE /:username/:projectName/file` - Delete a file
  * A rename can possibly be a `PUT` followed by a `DELETE` or we can expose another route
 * Publish:
  * `PUT /publish/:username/:projectName`
   * This probably needs discussion. I still think that we should have a `/.public/` folder in the *user's* filesystem that will contain snapshots of the published projects. This is what we should use for the public API to expose project files
  * `PUT /unpublish/:username/:projectName` - Probably just a recursive delete from the user's `/,public/` folder

 * Public API for any user
  * `GET /:username/:projectName` will show you the contents of `/.public/projectName/index.html` if it exists, 404 otherwise. I do not think that we should expose dir contents publicly because I don't think that there will be any use for it. On the other hand, something like `GET /:username/:projectName/style.css` would work.
  * `GET /remix/:username/:projectName`
   * I'm not too sure about this one. Maybe this can get a large json tree of the entire project?

@sedge anything to add?

**Comment by sedge** [comment]
Nope, this looks great IMO.

**Comment by humphd** [comment]
One question:

`GET /meta/:username/:projectName/dir` - List of contents of the dir. 404 if `dir` does not exist

Does this mean that your reporting of dir contents is shallow?  For a deep tree I'd need to make repeated calls to `/meta/:username/:projectName/.../dir`?  That's probably OK, but something to think about.

**Comment by gideonthomas** [comment]
No need, we can give a deep copy. Honestly not even sure if we are going to use that as I can't really think of a scenario where we would use it *atm*

**Comment by gideonthomas** [comment]
Actually, I think we should scrap that route. There doesn't seem to be a use case for this **and** we can always do a `readdir` locally to get the same info

**Comment by humphd** [comment]
As long as we can get remote details about the files to copy when we open a project we don't have locally.

**Comment by gideonthomas** [comment]
Yeah that's what I imagined `GET /remix/:username/:projectName` would do

**Comment by sedge** [comment]
@humphd Regarding opening a project: This API design, with or without our modifications, implies that we're going to index the project with the metadata route and pull down each file one by one with GET requests. I figure this is what we want. What do you think?

**Comment by jbuck** [comment]
I think that the concept of saving content and publishing content is complexity on the front-end and back-end that should be avoided.

But, if the concept of saving content and publishing content is key, then I think it's important that there are two separate servers, one for thimble to publish content to, and one for users to view content in their browser.

Riffing off @gideonthomas:

API for thimble to create, replace, update, and delete projects (publish.webmaker.org)

* GET /projects/:username
  * List the given users projects
* POST /projects/:username/:projectname
  * Create a project for the given user and project
* DELETE /projects/:username/:projectname
  * Delete a project for the given user and project
* POST /projects/:username/:projectname/publish
  * Publish the current saved version of the project
* I left out unpublish, because I think that's a complication that you don't need, but you could always add that in here.

API for thimble to list, create, replace, update, and delete files within projects (publish.webmaker.org)

* GET /files/:username/:projectname
  * Get the list of files for the given user and project. This is the entire file list for the project, so there's no recursive GET required here.
* GET /files/:username/:projectname/:file
  * Get the content for the given file
* PUT /files/:username/:projectname/:file
  * Create or replace the content for the given file, with the given Content-Type
* DELETE /files/:username/:projectname/:file
  * Delete the given file

API for users to view their content (makes.org)

* GET /:username/:project/:file

**Comment by simonwex** [comment]
<blockquote>Talking with @flukeout, there is another requirement that we need, specifically, a separation between content that is saved to the server, and content that is published. The goal of this separation is that a user be able to save frequently, and potentially save broken content, without affecting the published version until they are satisfied.</blockquote>

@jbuck why do you think this is complexity that should be avoided? We're designing this system to *support* users. In particular publishing on the web is hard and scary. this is where we should be doubling-down to make their lives easier.

**Comment by sedge** [comment]
This is long finished. Closing..
