### ISSUE TITLE
[META] Implement Thimble refresh

### ISSUE THREAD

**Issue by gideonthomas** [mozilla/thimble.webmaker.org#521]
* [ ] [Topbar ui/ux design](https://github.com/mozilla/thimble.webmaker.org/issues/526)
* [ ] [Editor modes UI](https://github.com/mozilla/thimble.webmaker.org/issues/513)
* [ ] [Tablet compatibility](https://github.com/mozilla/thimble.webmaker.org/issues/533)

**Comment by humphd** [comment]
Given that we have bugs on all these things, I don't think this bug is adding anything except noise in this milestone.  Closing, in favour of the related bugs.
