### ISSUE TITLE
MVP Feature List

### ISSUE THREAD

**Issue by flukeout** [mozilla/thimble.webmaker.org#563]
To ship an MVP we need to make sure that as I user, I can...

## Editor 

**User Account**
* [x] Sign in
  * [x] See my username and profile photo
* [x] Sign out
* [ ] ~~If my account has a language preference set, the editor will use it https://github.com/mozilla/thimble.webmaker.org/issues/662~~

**Currently Open Project** 
* [x] Rename the current project
* [x] Start a new, blank project
 * [x] What does a new project contain? #541
* [x] Changes to my project are auto-saved - #535
  * [x] See the "auto-saving" indicator - #571
* [ ] If I try to close the project or the tab while project is auto-saving, show a Javascript confirm warning me that I will lose work. 
 * https://github.com/mozilla/thimble.webmaker.org/issues/763

**My Projects List**
UX is tracked in #549 
* [x] See a list of my projects when they tap Your Projects in the user dropdown
* [ ] For each project in the list, I can...
  * [x] See the project title
  * [x] See when it was last-modified
  * [x] Open the project
  * [x] Delete the project
  * [ ] Remix the project (**Need to confirm what is expected here**)
* [ ] ~~Dismiss the list of my projects without opening one~~
* [ ] Projects are sorted by when they were last edited, with the most recently edited project listed at the top
  * https://github.com/mozilla/thimble.webmaker.org/issues/770

**Editor**
* [x] Open and close the editor setting menu
  * [x] Toggle the editor theme between dark and light
  * [x] Change the editor font size
* [x] Undo & redo work correctly
* [ ] ~~See useful error messages when mistakes are made - #572~~ 
* [ ] ~~View code hints when editing HTML, CSS & Javascript - #573~~
* [x] When hovering over HTML & CSS markup, the preview will show the corresponding areas
* [ ] ~~Add cool new html comments UI~~ - #738 

**Preview**
* [x] See changes in the preview as I modify code
* [x] Toggle preview between desktop and mobile mode
* [x] Press preview arrow to reload the preview

**Files**
* [x] Open & Close the file tray
* [x] Tap a file in the file tray to edit it
  * [x] Editor header will show the name of the file you are editing
* [x] Rename a file - #560
* [x] Delete a file - #559 
  * [ ] See a Javascript confirm dialog when doing this, filed in https://github.com/humphd/brackets/issues/400
* [x] Add a file - @flukeout to add tickets
  * [x] Drag a file from my computer to the file tray
  * [x] Add a HTML, CSS or JS file
  * [x] Choose a file to add from my computer's file system
* [x] See a file options menu by right clicking a file
* [x] File tray is open when loading or remixing a project with more than 1 file, collapsed if only 1 file

**Publishing**
* [x] Publish my project - UX in #539 
  * [x] See a link that I can follow to see the published version
* [x] Unpublish my project
* [x] Add a description to my project when publishing
* [ ] ~~Add tags to my project when publishing~~
* [ ] ~~Toggle if my project is visible in the gallery~~
* [x] See when I have unpublished changes, and publish them to the same URL
* [ ] If not signed in, should be prompted to sign in to publish - #512 
* [ ] ~~Rename project during publish?~~

**Published Project**
* [x] Published project has a Project details bar with the following **Exact spec TBD - Tracking in #570**
  * [x] Remix button 
  * [x] Project title
  * [x] Project author
  * [x] Link to Thimble home

**Gallery & Homepage**
* [ ] Create a homepage - #655

**Comment by hannahkane** [comment]
I might add:

**Onboarding**
* [ ] Understand what Thimble is
* [ ] See/search projects others have made, including filtering by tag
* [ ] Remix a project

**Editing**
* [ ] view code hints
* [ ] see useful errors

**Comment by flukeout** [comment]
@hannahkane Great, thanks - add more to your comment as you think of them, and I'll merge them into the master list a little later.

**Comment by jgmac1106** [comment]
I don't know if this is even possible, but....

For new users the code hints when you made mistakes were not always helpful
as they just redirected you to a list of acceptable properties, element,
and tags. I think the highlighting of the opening and closing tags is one
of the greatest of all the updates. That was the biggest error I saw.

I wonder if there could be a link to a discourse instance or category that
would like of work like stack overflow. When I couldn't figure something
out on Thimble I had a triage approach: Google it>ask on Twitter with
#teachtheweb>post to Discourse.

I just never knew exactly where in discourse to post code questions.
Luckily @toolness and others offered help. We  should try to curate a
community of users that can offer each other help. A button that linked to
an area in discourse would be cool.

**Comment by ashleygwilliams** [comment]
on `publish.wm.org` we currently have no representation of `remix`. will we be wanting to persist anything regards to that? on `api.wm.org` there is, e.g.: https://github.com/mozilla/api.webmaker.org/blob/develop/services/api/routes/public.js#L133

**Comment by toolness** [comment]
@jgmac1106, that's a great idea, and since we've now [migrated discourse to use webmaker for single-sign-on](https://github.com/mozilla/teach.webmaker.org/issues/930), we can even integrate directly with discourse in more programmatic ways if we want, which is nice.

**Comment by hannahkane** [comment]
This ticket feels superfluous to me now since everything in it is accounted for in other tickets with the  MVP label. @flukeout - are you ok with closing this?

**Comment by flukeout** [comment]
sure thing
